#Requires AutoHotkey v2.0
; Australian Spelling Converter
; Converts American spellings to Australian equivalents as you type
; Triggered when you finish typing a word (space, punctuation, etc.)
;
; Hotkeys:
;   Ctrl+Alt+A - Toggle converter on/off
;   Ctrl+Shift+A - Reload script (after adding new words)

; Ctrl+Alt+A - Toggle on/off
^!a:: {
    Suspend
    if A_IsSuspended
        TrayTip "Australian Spelling Converter", "Paused", 1
    else
        TrayTip "Australian Spelling Converter", "Active", 1
}
; Ctrl+Shift+A - Reload script (e.g. after editing to add words)
^+a::Reload()

; ============ -or to -our ============
Hotstring "::color", "colour"
Hotstring "::colors", "colours"
Hotstring "::colored", "coloured"
Hotstring "::coloring", "colouring"
Hotstring "::colorful", "colourful"
Hotstring "::favor", "favour"
Hotstring "::favors", "favours"
Hotstring "::favored", "favoured"
Hotstring "::favoring", "favouring"
Hotstring "::favorable", "favourable"
Hotstring "::favorably", "favourably"
Hotstring "::favorite", "favourite"
Hotstring "::favorites", "favourites"
Hotstring "::honor", "honour"
Hotstring "::honors", "honours"
Hotstring "::honored", "honoured"
Hotstring "::honoring", "honouring"
Hotstring "::honorable", "honourable"
Hotstring "::honorably", "honourably"
Hotstring "::labor", "labour"
Hotstring "::labors", "labours"
Hotstring "::labored", "laboured"
Hotstring "::laboring", "labouring"
Hotstring "::laborer", "labourer"
Hotstring "::laborers", "labourers"
Hotstring "::neighbor", "neighbour"
Hotstring "::neighbors", "neighbours"
Hotstring "::neighbored", "neighboured"
Hotstring "::neighboring", "neighbouring"
Hotstring "::flavor", "flavour"
Hotstring "::flavors", "flavours"
Hotstring "::flavored", "flavoured"
Hotstring "::behavior", "behaviour"
Hotstring "::behaviors", "behaviours"
Hotstring "::armor", "armour"
Hotstring "::armored", "armoured"
Hotstring "::harbor", "harbour"
Hotstring "::harbors", "harbours"
Hotstring "::humor", "humour"
Hotstring "::humors", "humours"
Hotstring "::humored", "humoured"
Hotstring "::odor", "odour"
Hotstring "::odors", "odours"
Hotstring "::parlor", "parlour"
Hotstring "::parlors", "parlours"
Hotstring "::rigor", "rigour"
Hotstring "::rigorous", "rigorous"  ; same
Hotstring "::rumor", "rumour"
Hotstring "::rumors", "rumours"
Hotstring "::savor", "savour"
Hotstring "::savors", "savours"
Hotstring "::splendor", "splendour"
Hotstring "::tumor", "tumour"
Hotstring "::tumors", "tumours"
Hotstring "::valor", "valour"
Hotstring "::vigor", "vigour"
Hotstring "::ardor", "ardour"
Hotstring "::clamor", "clamour"
Hotstring "::endeavor", "endeavour"
Hotstring "::endeavors", "endeavours"
Hotstring "::dolor", "dolour"

; ============ -er to -re ============
Hotstring "::center", "centre"
Hotstring "::centers", "centres"
Hotstring "::centered", "centred"
Hotstring "::centering", "centring"
Hotstring "::fiber", "fibre"
Hotstring "::fibers", "fibres"
Hotstring "::liter", "litre"
Hotstring "::liters", "litres"
Hotstring "::meter", "metre"
Hotstring "::meters", "metres"
Hotstring "::theater", "theatre"
Hotstring "::theaters", "theatres"
Hotstring "::caliber", "calibre"
Hotstring "::somber", "sombre"
Hotstring "::saber", "sabre"
Hotstring "::sabers", "sabres"
Hotstring "::luster", "lustre"
Hotstring "::specter", "spectre"
Hotstring "::specters", "spectres"

; ============ -ize to -ise ============
Hotstring "::realize", "realise"
Hotstring "::realizes", "realises"
Hotstring "::realized", "realised"
Hotstring "::realizing", "realising"
Hotstring "::organize", "organise"
Hotstring "::organizes", "organises"
Hotstring "::organized", "organised"
Hotstring "::organizing", "organising"
Hotstring "::organization", "organisation"
Hotstring "::organizations", "organisations"
Hotstring "::recognize", "recognise"
Hotstring "::recognizes", "recognises"
Hotstring "::recognized", "recognised"
Hotstring "::recognizing", "recognising"
Hotstring "::apologize", "apologise"
Hotstring "::apologizes", "apologises"
Hotstring "::apologized", "apologised"
Hotstring "::analyze", "analyse"
Hotstring "::analyzes", "analyses"
Hotstring "::analyzed", "analysed"
Hotstring "::analyzing", "analysing"
Hotstring "::authorize", "authorise"
Hotstring "::authorizes", "authorises"
Hotstring "::authorized", "authorised"
Hotstring "::capitalize", "capitalise"
Hotstring "::emphasize", "emphasise"
Hotstring "::emphasizes", "emphasises"
Hotstring "::emphasized", "emphasised"
Hotstring "::maximize", "maximise"
Hotstring "::maximizes", "maximises"
Hotstring "::maximized", "maximised"
Hotstring "::minimize", "minimise"
Hotstring "::minimizes", "minimises"
Hotstring "::minimized", "minimised"
Hotstring "::prioritize", "prioritise"
Hotstring "::prioritizes", "prioritises"
Hotstring "::prioritized", "prioritised"
Hotstring "::specialize", "specialise"
Hotstring "::specializes", "specialises"
Hotstring "::specialized", "specialised"
Hotstring "::stabilize", "stabilise"
Hotstring "::stabilizes", "stabilises"
Hotstring "::stabilized", "stabilised"
Hotstring "::customize", "customise"
Hotstring "::customizes", "customises"
Hotstring "::customized", "customised"
Hotstring "::standardize", "standardise"
Hotstring "::standardizes", "standardises"
Hotstring "::standardized", "standardised"
Hotstring "::summarize", "summarise"
Hotstring "::summarizes", "summarises"
Hotstring "::summarized", "summarised"
Hotstring "::utilize", "utilise"
Hotstring "::utilizes", "utilises"
Hotstring "::utilized", "utilised"
Hotstring "::criticize", "criticise"
Hotstring "::criticizes", "criticises"
Hotstring "::criticized", "criticised"
Hotstring "::memorize", "memorise"
Hotstring "::memorizes", "memorises"
Hotstring "::memorized", "memorised"
Hotstring "::categorize", "categorise"
Hotstring "::categorizes", "categorises"
Hotstring "::categorized", "categorised"

; ============ -og to -ogue ============
Hotstring "::catalog", "catalogue"
Hotstring "::catalogs", "catalogues"
Hotstring "::dialog", "dialogue"
Hotstring "::dialogs", "dialogues"
Hotstring "::monolog", "monologue"
Hotstring "::monologs", "monologues"
Hotstring "::analog", "analogue"
Hotstring "::analogs", "analogues"

; ============ -ense to -ence ============
Hotstring "::defense", "defence"
Hotstring "::defenses", "defences"
Hotstring "::offense", "offence"
Hotstring "::offenses", "offences"
Hotstring "::license", "licence"   ; noun form
Hotstring "::licenses", "licences"
Hotstring "::pretense", "pretence"
Hotstring "::pretenses", "pretences"

; ============ Double L (travelled, cancelled) ============
Hotstring "::traveled", "travelled"
Hotstring "::traveling", "travelling"
Hotstring "::traveler", "traveller"
Hotstring "::travelers", "travellers"
Hotstring "::canceled", "cancelled"
Hotstring "::canceling", "cancelling"
Hotstring "::counselor", "counsellor"
Hotstring "::counselors", "counsellors"
Hotstring "::marveled", "marvelled"
Hotstring "::marveling", "marvelling"
Hotstring "::modeled", "modelled"
Hotstring "::modeling", "modelling"
Hotstring "::signaled", "signalled"
Hotstring "::signaling", "signalling"
Hotstring "::labeled", "labelled"
Hotstring "::labeling", "labelling"
Hotstring "::jewelry", "jewellery"

; ============ Other common conversions ============
Hotstring "::gray", "grey"
Hotstring "::grays", "greys"
Hotstring "::grayed", "greyed"
Hotstring "::mold", "mould"
Hotstring "::molds", "moulds"
Hotstring "::molded", "moulded"
Hotstring "::molding", "moulding"
Hotstring "::molt", "moult"
Hotstring "::molts", "moults"
Hotstring "::molted", "moulted"
Hotstring "::maneuver", "manoeuvre"
Hotstring "::maneuvers", "manoeuvres"
Hotstring "::maneuvered", "manoeuvred"
Hotstring "::maneuvering", "manoeuvring"
Hotstring "::pediatric", "paediatric"
Hotstring "::pediatrics", "paediatrics"
Hotstring "::pedophile", "paedophile"
Hotstring "::estrogen", "oestrogen"
Hotstring "::anemia", "anaemia"
Hotstring "::anesthetic", "anaesthetic"
Hotstring "::anesthetics", "anaesthetics"
Hotstring "::archeology", "archaeology"
Hotstring "::encyclopedia", "encyclopaedia"
Hotstring "::medieval", "mediaeval"
Hotstring "::maneuverability", "manoeuvrability"

; ============ Aussie slang ============
Hotstring "::afternoon", "arvo"
Hotstring "::barbecue", "barbie"
Hotstring "::barbecues", "barbies"
Hotstring "::breakfast", "brekkie"
Hotstring "::McDonald's", "Maccas"
Hotstring "::McDonalds", "Maccas"
Hotstring "::sunglasses", "sunnies"
Hotstring "::television", "telly"
Hotstring "::umbrella", "brolly"
Hotstring "::umbrellas", "brollies"
Hotstring "::cigarette", "ciggie"
Hotstring "::cigarettes", "ciggies"
Hotstring "::sandwich", "sanger"
Hotstring "::sandwiches", "sangers"
Hotstring "::sausage", "snag"
Hotstring "::sausages", "snags"
Hotstring "::Christmas", "Chrissy"
Hotstring "::swimsuit", "cossie"
Hotstring "::swimsuits", "cossies"
Hotstring "::swimming costume", "cossie"
Hotstring "::swimming costumes", "cossies"
Hotstring "::flip-flop", "thong"
Hotstring "::flip-flops", "thongs"
Hotstring "::friend", "mate"
Hotstring "::friends", "mates"
Hotstring "::toilet", "dunny"
Hotstring "::toilets", "dunnies"
Hotstring "::bathroom", "loo"
Hotstring "::bathrooms", "loos"
Hotstring "::thank you", "ta"
Hotstring "::thanks", "ta"
Hotstring "::excellent", "ripper"
Hotstring "::a lot", "heaps"
Hotstring "::Australians", "Aussies"
Hotstring "::Australian", "Aussie"
Hotstring "::refrigerator", "fridge"
Hotstring "::refrigerators", "fridges"
Hotstring "::pacifier", "dummy"
Hotstring "::pacifiers", "dummies"
Hotstring "::alcohol", "grog"
Hotstring "::mosquito", "mozzie"
Hotstring "::mosquitoes", "mozzies"
Hotstring "::mosquitos", "mozzies"
Hotstring "::postman", "postie"
Hotstring "::postmen", "posties"
Hotstring "::pickup truck", "ute"
Hotstring "::pickup trucks", "utes"
Hotstring "::goodbye", "see ya"
Hotstring "::good bye", "see ya"
Hotstring "::no problem", "no worries"
Hotstring "::very good", "bonza"
Hotstring "::idiot", "drongo"
Hotstring "::idiots", "drongos"
Hotstring "::tired", "knackered"
Hotstring "::exhausted", "buggered"
Hotstring "::money", "dosh"

; Tray tip on startup
TrayTip "Australian Spelling Converter", "Active - spellings + slang", 1
